#!/usr/bin/env bash

# See https://shields.io/badges/static-badge for more info about the badge generation.

wget -O - https://img.shields.io/badge/Integration-Level_9-blue.svg        > level9.svg
wget -O - https://img.shields.io/badge/Integration-Level_8-brightgreen.svg > level8.svg
wget -O - https://img.shields.io/badge/Integration-Level_7-green.svg       > level7.svg
wget -O - https://img.shields.io/badge/Integration-Level_6-yellowgreen.svg > level6.svg
wget -O - https://img.shields.io/badge/Integration-Level_5-yellowgreen.svg > level5.svg
wget -O - https://img.shields.io/badge/Integration-Level_4-yellow.svg      > level4.svg
wget -O - https://img.shields.io/badge/Integration-Level_3-yellow.svg      > level3.svg
wget -O - https://img.shields.io/badge/Integration-Level_2-orange.svg      > level2.svg
wget -O - https://img.shields.io/badge/Integration-Level_1-orange.svg      > level1.svg
wget -O - https://img.shields.io/badge/Integration-Level_0-red.svg         > level0.svg
wget -O - https://img.shields.io/badge/Integration-Unknown-lightgrey.svg   > unknown.svg

wget -O - https://upload.wikimedia.org/wikipedia/commons/1/1d/No_image.svg > empty.svg
wget -O - https://img.shields.io/badge/Status-Package%20not%20maintained-red.svg > unmaintained.svg

wget -O - https://img.shields.io/badge/Status-working-brightgreen.svg      > state-working.svg
wget -O - https://img.shields.io/badge/Status-Just%20got%20added%20to%20catalog-yellowgreen.svg > state-just-got-added-to-catalog.svg
wget -O - https://img.shields.io/badge/Status-In%20progress-orange.svg     > state-inprogress.svg
wget -O - https://img.shields.io/badge/Status-Not%20working-red.svg        > state-notworking.svg
wget -O - https://img.shields.io/badge/Status-Broken-red.svg               > state-broken.svg

# Hexadecimal codes of colors to be used for badges. 
BLUE_LVL9=037CC2
GREEN_LVL8=338809
GREEN_LVL7=5D8210
YELLOWGREEN_LVL6=7A7B0D
YELLOWGREEN_LVL5=$YELLOWGREEN_LVL6
YELLOW_LVL4=867719
YELLOW_LVL3=$YELLOW_LVL4
ORANGE_LVL2=D04A0A
ORANGE_LVL1=$ORANGE_LVL2
RED_LVL0=DF351F
GREY_UNKNOWN=797676

# Add style and fancy logo
QUERY_PARAMS='style=for-the-badge&logo=yunohost'

wget -O - https://img.shields.io/badge/automatic_tests_level-9-$BLUE_LVL9.svg?$QUERY_PARAMS            > level9_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-8-$GREEN_LVL8.svg?$QUERY_PARAMS           > level8_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-7-$GREEN_LVL7.svg?$QUERY_PARAMS           > level7_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-6-$YELLOWGREEN_LVL6.svg?$QUERY_PARAMS     > level6_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-5-$YELLOWGREEN_LVL5.svg?$QUERY_PARAMS     > level5_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-4-$YELLOW_LVL4.svg?$QUERY_PARAMS          > level4_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-3-$YELLOW_LVL3.svg?$QUERY_PARAMS          > level3_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-2-$ORANGE_LVL2.svg?$QUERY_PARAMS          > level2_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-1-$ORANGE_LVL1.svg?$QUERY_PARAMS          > level1_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-0-$RED_LVL0.svg?$QUERY_PARAMS             > level0_v2.svg
wget -O - https://img.shields.io/badge/automatic_tests_level-unknown-$GREY_UNKNOWN.svg?$QUERY_PARAMS   > unknown_v2.svg
