#!/usr/bin/env bash

# Production -> download standalone tailwind to compile only what we need
curl --location -o tailwindcss-linux-x64 https://github.com/tailwindlabs/tailwindcss/releases/download/v3.4.3/tailwindcss-linux-x64
chmod +x tailwindcss-linux-x64

# Development -> we use the JS magic thingy
# curl -L https://cdn.tailwindcss.com?plugins=forms > tailwind-css.js

# Dark theme stuff
git clone https://github.com/jjranalli/nightwind

# Canvasjs (for the chart page only)
curl -L https://cdn.canvasjs.com/ga/canvasjs.min.js > canvasjs.min.js

# Icons / Forkawesome
curl https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/css/fork-awesome.min.css > fork-awesome.min.css
sed -i 's@../fonts/@@g' ./fork-awesome.min.css
curl https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/fonts/forkawesome-webfont.woff2?v=1.2.0 > forkawesome-webfont.woff2
curl https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/fonts/forkawesome-webfont.woff?v=1.2.0 > forkawesome-webfont.woff
curl https://cdn.jsdelivr.net/npm/fork-awesome@1.2.0/fonts/forkawesome-webfont.ttf?v=1.2.0 > forkawesome-webfont.ttf

# Logos
curl https://raw.githubusercontent.com/YunoHost/yunohost-artwork/refs/heads/main/logos/svg/yunohost-logo_black.svg > ynh_logo_black.svg


# Generate the whole
./tailwindcss-linux-x64 --input tailwind-local.css --output tailwind.css --minify
